// SPDX-License-Identifier: GPL-3.0-or-later

package taxonomy

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// LoadFile reads a taxonomy written by WriteFile.
func LoadFile(path string) (Taxonomy, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return Taxonomy{}, err
	}
	var t Taxonomy
	if err := yaml.Unmarshal(b, &t); err != nil {
		return Taxonomy{}, fmt.Errorf("%s: %w", path, err)
	}
	if len(t.Map) == 0 {
		return Taxonomy{}, fmt.Errorf("%s: no map entries", path)
	}
	return t, nil
}

// WriteFile renders the projection grouped by top level and subject, biggest
// first, with a comment line per top level — hand-readable and hand-editable.
// Every key and value is made of slug characters only, so plain YAML scalars
// are safe. Written atomically; the header lines go in as comments.
func WriteFile(path string, subjects []Cluster, header []string) error {
	type top struct {
		name     string
		views    int
		subjects []Cluster
	}
	byTop := map[string]*top{}
	for _, c := range subjects {
		t := byTop[c.Parent]
		if t == nil {
			t = &top{name: c.Parent}
			byTop[c.Parent] = t
		}
		t.views += c.Views
		t.subjects = append(t.subjects, c)
	}
	tops := make([]*top, 0, len(byTop))
	for _, t := range byTop {
		tops = append(tops, t)
	}
	sort.Slice(tops, func(i, j int) bool {
		if tops[i].views != tops[j].views {
			return tops[i].views > tops[j].views
		}
		return tops[i].name < tops[j].name
	})

	var b strings.Builder
	b.WriteString("# Generated by \"youtubehistii taxonomy\" — the projection \"old area/sub\"\n")
	b.WriteString("# -> \"new top/subject\". Verdicts stay untouched; report/watchpath apply\n")
	b.WriteString("# this on read via -taxonomy. Hand edits survive until the next run.\n")
	for _, h := range header {
		fmt.Fprintf(&b, "# %s\n", h)
	}
	b.WriteString("map:\n")
	for _, t := range tops {
		fmt.Fprintf(&b, "  # === %s (%d subjects, %d views) ===\n", t.name, len(t.subjects), t.views)
		for _, c := range t.subjects {
			target := c.Parent + "/" + c.Name
			if c.Name == c.Parent || c.Name == "" {
				target = c.Parent
			}
			froms := make([]string, len(c.Members))
			for i, l := range c.Members {
				froms[i] = l.Topic()
			}
			sort.Strings(froms)
			for _, from := range froms {
				fmt.Fprintf(&b, "  %s: %s\n", from, target)
			}
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(b.String()); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
