#!/usr/bin/env bash
#
# Generate the pre-push leak patterns for this repo from the LOCAL taxonomy.
#
# The subjects in config/taxonomy.yaml are one person's actual watch history.
# They belong in no comment, no fixture and no commit message — classify.go
# states the rule, and on 2026-08-28 the repo turned out not to have kept it
# (see the incident note referenced in README/AGENTS or ~/offline_coding/github).
#
# The point of generating rather than listing: a hand-kept list in ~/.env
# protects only the values somebody remembered to copy, is stale the moment
# the taxonomy changes, and is itself a second copy of the private data. This
# derives the patterns from the source, so the subject nobody thought of is
# covered too. The output goes inside the git dir, a path that cannot be
# committed — no .gitignore entry to forget.
#
# What is deliberately NOT protected: generic words that happen to also be
# somebody's subject. "chess", "jazz" and "factorio" are illustrations the
# tests use on purpose; blocking them would make the gate fire on every honest
# push, and a gate with routine false positives teaches --no-verify. Those live
# in scripts/leak-allow.txt, which is safe to commit precisely because it holds
# only generic terms.
#
# Run after the taxonomy changes:  scripts/gen-leak-patterns.sh
set -euo pipefail

cd "$(dirname "$0")/.."

taxonomy="config/taxonomy.yaml"
categories_src="internal/rules/youtube.go"
allow="scripts/leak-allow.txt"
out="$(git rev-parse --git-common-dir)/leak-patterns"

if [ ! -f "$taxonomy" ]; then
    printf 'gen-leak-patterns: no %s here — nothing private to derive patterns from.\n' "$taxonomy" >&2
    printf 'gen-leak-patterns: leaving %s untouched.\n' "$out" >&2
    exit 0
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Every "area/subject" pair in the taxonomy, reduced to the subject. Both sides
# of a mapping carry real subjects, so this reads the whole file rather than
# just the keys.
grep -oE '[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*' "$taxonomy" \
    | sed 's#.*/##' \
    | sort -u >"$tmp/subjects"

# YouTube's own category ids are public API values, not anybody's history —
# read from the source of truth rather than restated here, so a new category
# cannot silently start blocking pushes.
grep -oE '\{ID: "[a-z0-9-]+"' "$categories_src" \
    | sed 's/.*"\(.*\)"/\1/' \
    | sort -u >"$tmp/allow"

[ -f "$allow" ] && grep -vE '^[[:space:]]*(#|$)' "$allow" >>"$tmp/allow"
sort -u -o "$tmp/allow" "$tmp/allow"

# Specificity filter. Taking every subject verbatim does not work: a real
# history contains "art", "car", "backup", "cycling" — and "consume", which is
# this project's own vocabulary. Blocking those makes the gate fire on every
# honest push, which is worse than not having it.
#
# Two rules, and the split is deliberate:
#   - a MULTI-WORD slug is kept always. The most identifying value in this
#     corpus is a compound of two perfectly ordinary words and would fall
#     straight through a dictionary test; hyphenated compounds also almost
#     never turn up by accident in source.
#   - a SINGLE word is kept only if no dictionary knows it. That is what
#     separates a creator's name from "cycling" without anybody deciding it
#     by hand, and it is what keeps the short ones a word list would miss.
#
# Without a dictionary the second rule cannot run, and dropping every single
# word instead would silently lose exactly the creator names this exists for —
# so say so rather than reporting a smaller number as success.
dict=""
for cand in /usr/share/dict/words /usr/dict/words; do
    [ -f "$cand" ] && { dict="$cand"; break; }
done

grep -vxF -f "$tmp/allow" "$tmp/subjects" \
    | awk 'length($0) >= 3' >"$tmp/kept"

grep '-' "$tmp/kept" >"$tmp/specific" || true
if [ -n "$dict" ]; then
    tr '[:upper:]' '[:lower:]' <"$dict" | sort -u >"$tmp/dict"
    grep -v '-' "$tmp/kept" | grep -vxF -f "$tmp/dict" >>"$tmp/specific" || true
else
    printf 'gen-leak-patterns: no word list found — single-word subjects cannot be\n' >&2
    printf 'gen-leak-patterns: filtered and are ALL kept; expect false positives.\n' >&2
    grep -v '-' "$tmp/kept" >>"$tmp/specific" || true
fi

# Word-anchored, so a three-letter subject cannot fire inside "summary".
sort -u "$tmp/specific" | sed 's/^/\\b/; s/$/\\b/' >"$tmp/patterns"

{
    printf '# Generated by scripts/gen-leak-patterns.sh — do not hand-edit.\n'
    printf '# Source: %s (local, never committed). Regenerate after it changes.\n' "$taxonomy"
    cat "$tmp/patterns"
} >"$out"

# Counts only: the values are the thing being protected and must not reach a
# terminal, a log or a transcript.
printf 'gen-leak-patterns: %s subjects, %s allowed, %s patterns -> %s\n' \
    "$(wc -l <"$tmp/subjects" | tr -d ' ')" \
    "$(wc -l <"$tmp/allow" | tr -d ' ')" \
    "$(wc -l <"$tmp/patterns" | tr -d ' ')" \
    "$out"
